version: "3"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1Zhongguo
      MYSQL_DATABASE: PWeb
      MYSQL_USER: PWeb
      MYSQL_PASSWORD: 1Zhongguo

  phpapp:
    image: myappcrise
    build: .
    command: php -S 0.0.0.0:8080 -t /var/www/html/public
    volumes:
      - .:/var/www/html
    ports:
      - '8000:8080'


